#!/bin/bash

# Balazs Adam-Attila
# baam0146
# 

awk -v skipnext=0 '{

string=""

if ( $1 == "+" ){
	for (i = 2; i < NF; i=i+2) {
		string = string FS $(i+1) FS $i
	}
	
	if (NF % 2 == 0){
		string = string FS $NF
	}
	
	skipnext = 1
	print string
}
else if (skipnext == 1) {
	skipnext = 0
	print $0
}
else {
	for (i = NF; i > 0; i=i-1) {
		string = string FS $i
	}

        skipnext = 0
	print string
}


}
' $1
