#!/bin/bash

# Balazs Adam-Attila
# baam0146
# Írjunk "awk"-t meghívó shell scriptet, mely a kodolt nevű "kódolt"
# állomány sorait a következő szabály szerint dolgozza fel:
# - a "+" jellel kezdődő sorokban páronként felcseréli a szavak
# sorrendjét (a "+" jelet elhagyva)
# - a "+" jellel jelölt sorok után következő sort (ha az nincs szintén
# megjelölve)  változatlanul hagyja
# - az összes többi sorban megfordítja a szavak sorrendjét

awk -v skipnext=0 '{

string=""

if ( $1 == "+" ){
	for (i = 2; i < NF; i=i+2) {
		string = string FS $(i+1) FS $i
	}
	
	if (NF % 2 == 0){
		string = string FS $NF
	}
	
	skipnext = 1
	print string
}
else if (skipnext == 1) {
	skipnext = 0
	print $0
}
else {
	for (i = NF; i > 0; i=i-1) {
		string = string FS $i
	}

        skipnext = 0
	print string
}


}
' kodolt
